### ISSUE TITLE
Grasshopper_Toolkit - Create a component to allow safe input and storage of password to access things like an external Mongo server

### ISSUE THREAD

**Issue by adecler** [BHoM/Grasshopper_UI#107]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by epignatelli** [comment]
@adecler @IsakNaslundBh Is this being solved in https://github.com/BHoM/BHoM_Engine/pull/782?

**Comment by IsakNaslundBh** [comment]
@epignatelli think this is something different, dealing with being able to input and store data that should not be accessible/view-able from the UI's etc.

**Comment by epignatelli** [comment]
Sorry, I clearly commented on the wrong issue. I am deleting it and moving it to the right one.

**Comment by adecler** [comment]
Yes, this is definitely not a Grasshopper issue anymore. Most likely going to sit in the BHoM_Engine. 
I have already something similar for Code_Server and GitHub_Toolkit but will need to look into it to refine the details on how it works on a UI level. 
Do you mind keeping it here and assigned to me until I come back to it and figure this out ?

**Comment by epignatelli** [comment]
Yeah, yeah, no rush! It all started by me commenting on the wrong issue, so definitely happy to leave it here!

**Comment by adecler** [comment]
Currently not on the roadmap. Will create new issue if/when this becomes relevant again.
