### ISSUE TITLE
Grasshopper_Toolkit: Use grasshopper GH to build a computation graph, and don't compute it, but save it and run it somewhere else

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Grasshopper_UI#251]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
@epignatelli , if I understood you correctly, this is going to be covered by node 2 code, right?
See specifically https://github.com/BHoM/Grasshopper_Toolkit/issues/123.
If this is correct, can we close this issue? Otherwise can we refine the scope here?

**Comment by epignatelli** [comment]
This was specifically to serialise the syntax tree in one software, say Grasshopper, and deserialise it into another one, say Dynamo or Excel.

The purpose was two-fold: to make scripts inter-operable, and to serialise scripts as jobs that can be sent for high performance computing.

Although, I don't think this was more a call for discussion rather than a feature requests, and may not be immediately relevant.

**Comment by adecler** [comment]
Closing as there is no plan to have this on the roadmap
