### ISSUE TITLE
Grasshopper_Toolkit: Handle rendering of TextTags and ColouredGeometry 

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_UI#420]
#### Description:

When https://github.com/BHoM/BHoM/issues/568 and https://github.com/BHoM/BHoM/issues/569 has been added, custom rendering of them needs to be implemented in GH.

**Comment by adecler** [comment]
@IsakNaslundBh , I'll let you decide if this is still relevant or not

**Comment by IsakNaslundBh** [comment]
Think this can be closed as of https://github.com/BHoM/Grasshopper_UI/pull/602
