### ISSUE TITLE
BHoM_UI: Align icons to BHoM logo

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Grasshopper_UI#421]
#### Broken rules:

Icons do not currently reflect the graphic identity of https://bhom.xyz.

#### Suggestions to restore compliance:

Using the coral color, the BHoM "dot" logo and a bit of creativity would help re-aligning the icons to the general BHoM graphic.

**Comment by adecler** [comment]
Closing as this not in the roadmap and has been stale for a few years.
