### ISSUE TITLE
Grasshopper_Toolkit: Is there a way to "Select" BHoM objects?

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/Grasshopper_UI#503]
For BHoM objects that have a geometry representation, in some cases it will be very helpful to be able select BHoM objects. Here is a very interesting grasshopper plugin that allows you to select Mesh but I wonder if it is worth to explore this possibility in BHoM.

https://www.food4rhino.com/app/mouse-rat

**Comment by adecler** [comment]
Closing as BHoM objects are now rendered in the Rhino viewport
